# Generated by Django 5.0.6 on 2024-06-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maps',
            name='maps',
        ),
    ]
