# Generated by Django 5.0.6 on 2024-06-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_maps_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='maps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
