# Generated by Django 5.0.6 on 2024-06-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_maps_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='maps',
            field=models.CharField(max_length=200),
        ),
    ]
